### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yusukebe** [honojs/middleware-template#1]
- [x] deno_test
- [x] ~~bun_test~~
- [x] CI for Deno
- [x] ~~CI for Bun~~
- [x] ~~jest environment miniflare => wrangler~~
- [x] Instruction for developers
- [x] ~~GitHub Actions for publish to npm repository~~
